version: '3.8'

services:
  server:
    image: ryan-server:latest
    ports:
      - 443:443
    volumes:
      - ./db/db_file.db:/etc/twitch_gameserver/db_data/db_file.db
      - /etc/letsencrypt/live/spirodon.games/privkey.pem:/etc/twitch_gameserver/ssl_certs/privkey.pem
      - /etc/letsencrypt/live/spirodon.games/fullchain.pem:/etc/twitch_gameserver/ssl_certs/fullchain.pem
